### ISSUE TITLE
sort plus installed but not appearing

### ISSUE THREAD

**Issue by Molynesio** [Delusoire/spicetify-extensions#28] opened 2024-03-18 02:35 UTC
The sign plus button doesnt appear neither  the right click features and the settings for the extension in my profile. I saw a closed issue where the person reinstalled completely, also worked for me but the problem  is not first time that happened to me, happens randomly when installing apps or updating spicetify (i dont actually remember when) so i dont want to reinstall every extension when that happens (also when reinstalling backups doesnt seem to make it work neither) Any help gladly appreciated.
Update installed from 22 february 2024
Spotify para Windows (64 bits)
1.2.33.1039.g8ddb5918
Spicetify v2.34.1

**Comment by zachpoblete** [comment] 2024-04-02 09:12
Duplicate of #27?

**Comment by Delusoire** [comment] 2024-04-03 09:43
I'm currently working on Spicetify v3, I have already ported all of my extensions (and then some) to the new version. Thus this repo won't be getting any updates. But if anyone's willing to open a PR fixing this issue then I'd be more than willing to merge it.

**Closed as completed by Delusoire** 2024-04-03 09:43 UTC
