### ISSUE TITLE
[Feature Request] Sort by play count with options

### ISSUE THREAD

**Issue by SuperPantsBG** [Delusoire/spicetify-extensions#4] opened 2023-08-27 13:26 UTC
I think a great addition will be to be able to choose whether u want your sorting by play count to be ascending or descending.

**Comment by Delusoire** [comment] 2023-08-28 08:29
Duplicate of #3

**Closed as completed by Delusoire** 2023-08-28 08:29 UTC

**Comment by SuperPantsBG** [comment] 2023-08-28 20:36
> Duplicate of #3

Oh, I'm sorry.
There were only 2 request when I looked so I thought no one has requested about it.
